version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  build:
    commands:
      - echo "Building the static website..."
      - cp index.html .
      - cp styles.css .
      - cp readme.md .

artifacts:
  files:
    - index.html
    - styles.css
    - readme.md
